"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { MALE_FRONT, MALE_BACK } from "@musclemap/assets";
import type { BodyDiagram } from "@musclemap/assets";

type Exercise={name:string;sets:string;reps:string;completed:boolean};
type RadarKey="胸"|"背"|"肩"|"手臂"|"核心"|"腿";
type Course={student:string;coach?:string;dateTime:string;goal:string;planText:string;plannedDays:number[];missedDays:number[];skippedDays?:number[];exercises:Exercise[];radar:Record<RadarKey,number>;growth:Record<RadarKey,number>;muscles:string[];summary:string;nextPlan:string};
const axes:RadarKey[]=["胸","背","肩","手臂","核心","腿"];
const muscleGroups=["胸大肌","肩前束","肩中束","肩后束","肱二头肌","肱三头肌","前臂","腹直肌","腹外斜肌","斜方肌","背阔肌","竖脊肌","臀大肌","臀中肌","股四头肌","内收肌","腘绳肌","胫骨前肌","腓肠肌"];
const muscleCode:Record<string,string>={胸大肌:"CHEST",肩前束:"SHOULDERS_FRONT",肩中束:"SHOULDERS_SIDE",肩后束:"SHOULDERS_REAR",肱二头肌:"BICEPS",肱三头肌:"TRICEPS",前臂:"FOREARMS",腹直肌:"CORE",腹外斜肌:"OBLIQUES",斜方肌:"TRAPEZIUS",背阔肌:"LATS",竖脊肌:"BACK_LOWER",臀大肌:"GLUTES",臀中肌:"ABDUCTORS",股四头肌:"QUADS",内收肌:"ADDUCTORS",腘绳肌:"HAMSTRINGS",胫骨前肌:"CALVES",腓肠肌:"CALVES"};
const nowLocal=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const initial:Course={student:"王小明",dateTime:nowLocal(),goal:"提升下肢力量与髋部稳定",planText:"每周训练三次",plannedDays:[3,6,10,13,17,20],missedDays:[8,15],exercises:[{name:"高脚杯深蹲",sets:"4",reps:"12",completed:true},{name:"罗马尼亚硬拉",sets:"4",reps:"10",completed:true},{name:"保加利亚分腿蹲",sets:"3",reps:"10",completed:true},{name:"平板支撑",sets:"3",reps:"45秒",completed:true}],radar:{胸:48,背:58,肩:55,手臂:52,核心:61,腿:64},growth:{胸:3,背:3,肩:3,手臂:3,核心:7,腿:9},muscles:["腹直肌","臀大肌","臀中肌","股四头肌","腘绳肌"],summary:"动作控制稳定，深蹲幅度明显提升；后两组核心略有松动，继续保持呼吸节奏。",nextPlan:"单腿稳定进阶 · 臀腿力量强化 · 核心抗旋转"};
const lime="#b7db3f",ink="#050505",white="#f5f5f2";
function wrap(ctx:CanvasRenderingContext2D,text:string,max:number,limit=3){const out:string[]=[];let line="";for(const c of [...text]){if(ctx.measureText(line+c).width>max&&line){out.push(line);line=c}else line+=c;if(out.length===limit)break}if(out.length<limit&&line)out.push(line);return out}
function polygon(ctx:CanvasRenderingContext2D,cx:number,cy:number,r:number,values:number[]){ctx.beginPath();values.forEach((v,i)=>{const a=-Math.PI/2+i*Math.PI/3,x=cx+Math.cos(a)*r*v/100,y=cy+Math.sin(a)*r*v/100;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath()}
function ellipse(ctx:CanvasRenderingContext2D,x:number,y:number,rx:number,ry:number,color:string){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();ctx.strokeStyle="#77776f";ctx.lineWidth=1;ctx.stroke()}
function muscle(ctx:CanvasRenderingContext2D,on:boolean,x:number,y:number,rx:number,ry:number,rot=0){ctx.beginPath();ctx.ellipse(x,y,rx,ry,rot,0,Math.PI*2);ctx.fillStyle=on?lime:"#282824";ctx.fill();ctx.strokeStyle=on?"#d8fa65":"#66665e";ctx.lineWidth=1.2;ctx.stroke()}
function drawBody(ctx:CanvasRenderingContext2D,cx:number,top:number,front:boolean,selected:Set<string>){
 const base="#20201d",on=(name:string)=>selected.has(name);ellipse(ctx,cx,top+24,18,23,base);ctx.fillStyle=base;ctx.fillRect(cx-9,top+43,18,14);
 ctx.beginPath();ctx.moveTo(cx-10,top+55);ctx.lineTo(cx-48,top+72);ctx.lineTo(cx-38,top+174);ctx.lineTo(cx-22,top+218);ctx.lineTo(cx+22,top+218);ctx.lineTo(cx+38,top+174);ctx.lineTo(cx+48,top+72);ctx.lineTo(cx+10,top+55);ctx.closePath();ctx.fill();ctx.strokeStyle="#77776f";ctx.stroke();
 [[-52,94,-62,180], [52,94,62,180],[-22,215,-27,340],[22,215,27,340]].forEach(p=>{ctx.strokeStyle=base;ctx.lineWidth=22;ctx.beginPath();ctx.moveTo(cx+p[0],top+p[1]);ctx.lineTo(cx+p[2],top+p[3]);ctx.stroke();ctx.strokeStyle="#77776f";ctx.lineWidth=1;ctx.stroke()});
 if(front){muscle(ctx,on("胸大肌"),cx-17,top+91,18,16,-.18);muscle(ctx,on("胸大肌"),cx+17,top+91,18,16,.18);muscle(ctx,on("肩前束"),cx-39,top+78,10,14,-.45);muscle(ctx,on("肩前束"),cx+39,top+78,10,14,.45);muscle(ctx,on("肩中束"),cx-48,top+87,8,15,-.2);muscle(ctx,on("肩中束"),cx+48,top+87,8,15,.2);muscle(ctx,on("肱二头肌"),cx-53,top+124,8,22,.12);muscle(ctx,on("肱二头肌"),cx+53,top+124,8,22,-.12);muscle(ctx,on("前臂"),cx-59,top+164,7,23,.1);muscle(ctx,on("前臂"),cx+59,top+164,7,23,-.1);for(let i=0;i<3;i++){muscle(ctx,on("腹直肌"),cx-8,top+128+i*25,7,11);muscle(ctx,on("腹直肌"),cx+8,top+128+i*25,7,11)}muscle(ctx,on("腹外斜肌"),cx-23,top+151,9,35,.12);muscle(ctx,on("腹外斜肌"),cx+23,top+151,9,35,-.12);muscle(ctx,on("股四头肌"),cx-24,top+250,11,37,.05);muscle(ctx,on("股四头肌"),cx+24,top+250,11,37,-.05);muscle(ctx,on("内收肌"),cx-10,top+245,7,32,-.12);muscle(ctx,on("内收肌"),cx+10,top+245,7,32,.12);muscle(ctx,on("胫骨前肌"),cx-28,top+310,7,27,.06);muscle(ctx,on("胫骨前肌"),cx+28,top+310,7,27,-.06)}else{muscle(ctx,on("肩后束"),cx-42,top+82,12,14,-.35);muscle(ctx,on("肩后束"),cx+42,top+82,12,14,.35);muscle(ctx,on("斜方肌"),cx,top+91,24,30);muscle(ctx,on("背阔肌"),cx-25,top+133,15,40,-.12);muscle(ctx,on("背阔肌"),cx+25,top+133,15,40,.12);muscle(ctx,on("肱三头肌"),cx-54,top+125,8,25,.12);muscle(ctx,on("肱三头肌"),cx+54,top+125,8,25,-.12);muscle(ctx,on("竖脊肌"),cx-8,top+164,6,38);muscle(ctx,on("竖脊肌"),cx+8,top+164,6,38);muscle(ctx,on("臀中肌"),cx-22,top+207,12,14,-.25);muscle(ctx,on("臀中肌"),cx+22,top+207,12,14,.25);muscle(ctx,on("臀大肌"),cx-18,top+224,17,18);muscle(ctx,on("臀大肌"),cx+18,top+224,17,18);muscle(ctx,on("腘绳肌"),cx-24,top+265,10,35,.05);muscle(ctx,on("腘绳肌"),cx+24,top+265,10,35,-.05);muscle(ctx,on("腓肠肌"),cx-28,top+320,8,23,.08);muscle(ctx,on("腓肠肌"),cx+28,top+320,8,23,-.08)}
 ctx.fillStyle="#bdbdb7";ctx.font="500 15px 'Focus Sans'";ctx.textAlign="center";ctx.fillText(front?"正面":"背面",cx,top+372);ctx.textAlign="left";
}
function drawAtlas(ctx:CanvasRenderingContext2D,diagram:BodyDiagram,x:number,y:number,w:number,h:number,selected:Set<string>){
 const [vx,vy,vw,vh]=diagram.viewBox.split(/\s+/).map(Number),sx=w/vw,sy=h/vh;ctx.save();ctx.translate(x-vx*sx,y-vy*sy);ctx.scale(sx,sy);const paint=(d:string,fill:string,stroke="#10100f")=>{const p=new Path2D(d);ctx.fillStyle=fill;ctx.fill(p);ctx.strokeStyle=stroke;ctx.lineWidth=1.2/sx;ctx.stroke(p)};diagram.outline.forEach(part=>{paint(part.d,"#20201d","#77776f");if(part.side==="LEFT"){ctx.save();ctx.translate(2*diagram.centerX,0);ctx.scale(-1,1);paint(part.d,"#20201d","#77776f");ctx.restore()}});diagram.muscles.forEach(part=>{const active=selected.has(part.group),fill=active?lime:"#34342f";paint(part.d,fill,active?"#e1ff73":"#161614");if(part.side==="LEFT"){ctx.save();ctx.translate(2*diagram.centerX,0);ctx.scale(-1,1);paint(part.d,fill,active?"#e1ff73":"#161614");ctx.restore()}});ctx.restore();
}
function drawCalendar(ctx:CanvasRenderingContext2D,dateTime:string,completed:number[],upcoming:number[],skipped:number[],x:number,y:number,w:number){const d=new Date(dateTime||Date.now()),year=d.getFullYear(),month=d.getMonth(),days=new Date(year,month+1,0).getDate(),start=new Date(year,month,1).getDay(),cell=w/7;ctx.fillStyle=white;ctx.font="700 21px 'Focus Sans'";ctx.fillText(`${year}年 ${month+1}月`,x,y);ctx.font="500 13px 'Focus Sans'";ctx.fillStyle="#85857f";["日","一","二","三","四","五","六"].forEach((t,i)=>{ctx.textAlign="center";ctx.fillText(t,x+cell*(i+.5),y+30)});for(let day=1;day<=days;day++){const n=start+day-1,col=n%7,row=Math.floor(n/7),cx=x+cell*(col+.5),cy=y+57+row*34,isDone=completed.includes(day),isNext=upcoming.includes(day),isSkipped=skipped.includes(day);if(isDone||isNext||isSkipped){ctx.beginPath();ctx.arc(cx,cy-5,12,0,Math.PI*2);ctx.lineWidth=2;ctx.strokeStyle=isSkipped?"#ff2ca8":lime;if(isDone||isSkipped){ctx.fillStyle=isSkipped?"#ff2ca8":lime;ctx.fill()}else ctx.stroke()}ctx.fillStyle=isDone?ink:white;ctx.font="600 13px Arial";ctx.textAlign="center";ctx.fillText(String(day),cx,cy)}ctx.textAlign="left"}
function drawPoster(canvas:HTMLCanvasElement,data:Course,logo?:HTMLImageElement){
 const ctx=canvas.getContext("2d");if(!ctx)return;canvas.width=1080;canvas.height=1920;ctx.fillStyle=ink;ctx.fillRect(0,0,1080,1920);ctx.lineCap="square";ctx.lineJoin="miter";
 // Use the supplied FOCUS artwork itself. Crop away only its original empty black margin.
 if(logo?.complete)ctx.drawImage(logo,285,155,510,770,55,38,136,190);
 ctx.strokeStyle="#656560";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(214,50);ctx.lineTo(214,232);ctx.stroke();ctx.fillStyle=white;ctx.font="900 72px 'Focus Sans',sans-serif";ctx.fillText(data.student||"未命名",252,145,420);ctx.fillStyle="#a7a7a1";ctx.font="500 22px 'Focus Sans'";ctx.fillText(`教练：${data.coach||"冷教练"}`,255,190);const dt=(data.dateTime||"").replace("-",".").replace("-",".").replace("T","  ");ctx.textAlign="right";ctx.font="500 29px 'Arial Narrow',Arial";ctx.fillStyle=white;ctx.fillText(dt,1018,145);ctx.textAlign="left";ctx.strokeStyle=lime;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(55,251);ctx.lineTo(615,251);ctx.lineTo(688,200);ctx.lineTo(1018,200);ctx.stroke();
 // Goal band with the same sharp clipped corners as the reference.
 ctx.beginPath();ctx.moveTo(55,292);ctx.lineTo(936,292);ctx.lineTo(1018,335);ctx.lineTo(1018,410);ctx.lineTo(55,410);ctx.closePath();ctx.strokeStyle=lime;ctx.stroke();ctx.beginPath();ctx.moveTo(55,292);ctx.lineTo(322,292);ctx.lineTo(275,410);ctx.lineTo(55,410);ctx.closePath();ctx.fillStyle=lime;ctx.fill();ctx.beginPath();ctx.moveTo(936,292);ctx.lineTo(958,292);ctx.lineTo(1018,323);ctx.lineTo(1018,335);ctx.closePath();ctx.fill();ctx.fillStyle=ink;ctx.font="900 36px 'Focus Sans'";ctx.fillText("本节目标",83,365);ctx.fillStyle=white;ctx.font="900 39px 'Focus Sans'";ctx.fillText(data.goal,340,365,610);
 // Monthly plan at left, completed exercises at right.
 ctx.fillStyle=lime;ctx.font="900 36px 'Focus Sans'";ctx.fillText("训练规划",55,500);ctx.fillText("训练内容",395,500);ctx.strokeStyle=lime;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(55,520);ctx.lineTo(190,520);ctx.lineTo(212,498);ctx.lineTo(350,498);ctx.moveTo(395,520);ctx.lineTo(570,520);ctx.lineTo(592,498);ctx.lineTo(1018,498);ctx.stroke();ctx.beginPath();ctx.moveTo(365,455);ctx.lineTo(365,915);ctx.stroke();drawCalendar(ctx,data.dateTime,data.plannedDays||[],data.missedDays||[],data.skippedDays||[],65,555,270);
 data.exercises.slice(0,6).forEach((x,i)=>{const y=575+i*58;ctx.fillStyle=white;ctx.font="700 23px 'Focus Sans'";ctx.fillText(x.name||"训练动作",395,y,250);ctx.fillStyle=lime;ctx.font="750 21px 'Focus Sans'";ctx.fillText(`${x.sets||"—"}×${x.reps||"—"}`,710,y,125);ctx.textAlign="right";ctx.fillStyle=x.completed?white:"#777";ctx.font="500 18px 'Focus Sans'";ctx.fillText(x.completed?"已完成":"未完成",985,y);ctx.textAlign="left";ctx.strokeStyle="#333330";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(395,y+23);ctx.lineTo(1018,y+23);ctx.stroke();ctx.fillStyle=x.completed?lime:"#343432";ctx.fillRect(395,y+16,520,7);if(x.completed){ctx.strokeStyle=lime;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(950,y+9);ctx.lineTo(960,y+19);ctx.lineTo(978,y-1);ctx.stroke()}});
 // Radar and anatomical atlas share one row.
 ctx.fillStyle=lime;ctx.font="900 36px 'Focus Sans'";ctx.fillText("能力变化图",55,980);ctx.fillText("本节训练肌群",535,980);ctx.strokeStyle=lime;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(55,998);ctx.lineTo(225,998);ctx.lineTo(247,978);ctx.lineTo(470,978);ctx.moveTo(535,998);ctx.lineTo(755,998);ctx.lineTo(777,978);ctx.lineTo(1018,978);ctx.stroke();ctx.beginPath();ctx.moveTo(500,940);ctx.lineTo(500,1435);ctx.stroke();
 const cx=263,cy=1210,r=145;ctx.strokeStyle="#575752";ctx.lineWidth=1;for(let l=1;l<=5;l++){polygon(ctx,cx,cy,r,axes.map(()=>l*20));ctx.stroke()}axes.forEach((a,i)=>{const q=-Math.PI/2+i*Math.PI/3;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(q)*r,cy+Math.sin(q)*r);ctx.stroke();const lr=r+31,x=cx+Math.cos(q)*lr,y=cy+Math.sin(q)*lr;ctx.fillStyle=white;ctx.font="700 18px 'Focus Sans'";ctx.textAlign=Math.cos(q)>.25?"left":Math.cos(q)<-.25?"right":"center";ctx.textBaseline=Math.sin(q)>.5?"top":Math.sin(q)<-.5?"bottom":"middle";ctx.fillText(a,x,y)});ctx.textBaseline="alphabetic";ctx.textAlign="left";const current=axes.map(a=>data.radar[a]),projected=axes.map(a=>Math.min(100,data.radar[a]+data.growth[a]));polygon(ctx,cx,cy,r,current);ctx.fillStyle="rgba(183,219,63,.38)";ctx.fill();ctx.strokeStyle=lime;ctx.lineWidth=3;ctx.stroke();polygon(ctx,cx,cy,r,projected);ctx.strokeStyle=lime;ctx.lineWidth=3;ctx.setLineDash([12,10]);ctx.stroke();ctx.setLineDash([]);axes.forEach((a,i)=>{const q=-Math.PI/2+i*Math.PI/3,iv=data.radar[a],ov=Math.min(100,iv+data.growth[a]),innerR=Math.max(18,r*iv/100-22),ix=cx+Math.cos(q)*innerR,iy=cy+Math.sin(q)*innerR,ox=cx+Math.cos(q)*(r*ov/100+14),oy=cy+Math.sin(q)*(r*ov/100+14);ctx.textAlign="center";ctx.textBaseline="middle";ctx.font="800 14px Arial";ctx.fillStyle=white;ctx.fillText(String(iv),ix,iy);ctx.fillStyle=lime;ctx.fillText(String(ov),ox,oy)});ctx.textBaseline="alphabetic";ctx.textAlign="left";ctx.fillStyle=lime;ctx.fillRect(110,1400,52,8);ctx.fillStyle=white;ctx.font="500 17px 'Focus Sans'";ctx.fillText("当前",175,1410);ctx.strokeStyle=lime;ctx.setLineDash([10,8]);ctx.beginPath();ctx.moveTo(285,1405);ctx.lineTo(337,1405);ctx.stroke();ctx.setLineDash([]);ctx.fillText("课后预估",350,1410);
 const selectedCodes=new Set((data.muscles||[]).map(m=>muscleCode[m]).filter(Boolean));drawAtlas(ctx,MALE_FRONT,545,1010,205,360,selectedCodes);drawAtlas(ctx,MALE_BACK,765,1010,205,360,selectedCodes);ctx.fillStyle="#aaa9a2";ctx.font="500 15px 'Focus Sans'";ctx.textAlign="center";ctx.fillText("正面",648,1390);ctx.fillText("背面",868,1390);ctx.textAlign="left";ctx.fillStyle=white;ctx.font="600 17px 'Focus Sans'";ctx.fillText((data.muscles||[]).join(" · ")||"未选择肌群",550,1422,445);
 const block=(y:number,h:number,title:string,text:string,font=25)=>{ctx.beginPath();ctx.moveTo(55,y);ctx.lineTo(937,y);ctx.lineTo(1018,y+42);ctx.lineTo(1018,y+h);ctx.lineTo(55,y+h);ctx.closePath();ctx.strokeStyle=lime;ctx.lineWidth=2;ctx.stroke();ctx.beginPath();ctx.moveTo(937,y);ctx.lineTo(959,y);ctx.lineTo(1018,y+31);ctx.lineTo(1018,y+42);ctx.closePath();ctx.fillStyle=lime;ctx.fill();const small=h<120,titleY=small?y+42:y+60,lineY=small?y+34:y+49,textY=small?y+82:y+112;ctx.font=`900 ${small?30:38}px 'Focus Sans'`;ctx.fillText(title,85,titleY);ctx.beginPath();ctx.moveTo(small?270:300,lineY);ctx.lineTo(920,lineY);ctx.stroke();ctx.fillStyle=white;ctx.font=`500 ${font}px 'Focus Sans'`;wrap(ctx,text,860,h>160?3:1).forEach((t,i)=>ctx.fillText(t,85,textY+i*39))};block(1500,190,"教练总结",data.summary,26);block(1715,105,"下节计划",data.nextPlan,22);
}
export default function Home(){
 const[course,setCourse]=useState<Course>(initial),[notice,setNotice]=useState(""),[logo,setLogo]=useState<HTMLImageElement>();const canvas=useRef<HTMLCanvasElement>(null);useEffect(()=>{const image=new Image();image.src="/focus-logo.png";image.onload=()=>setLogo(image)},[]);useEffect(()=>{if(canvas.current)drawPoster(canvas.current,course,logo)},[course,logo]);const patch=<K extends keyof Course>(key:K,value:Course[K])=>setCourse(x=>({...x,[key]:value}));const patchEx=(i:number,key:keyof Exercise,value:string|boolean)=>patch("exercises",course.exercises.map((x,j)=>j===i?{...x,[key]:value}:x));const flash=(x:string)=>{setNotice(x);window.setTimeout(()=>setNotice(""),2200)};const save=()=>{localStorage.setItem("focus-course-draft",JSON.stringify(course));flash("草稿已保存到本机")};const load=()=>{const v=localStorage.getItem("focus-course-draft");if(v){setCourse(JSON.parse(v));flash("已恢复本机草稿")}};const download=()=>{const a=document.createElement("a");a.download=`${course.student}-${course.dateTime.slice(0,10)}-训练总结.png`;a.href=canvas.current?.toDataURL("image/png")||"";a.click();flash("高清图片已生成")};const shownTime=useMemo(()=>course.dateTime.replace("T"," "),[course.dateTime]);
 return <main className="shell"><aside className="sidebar"><div className="brand"><b>F</b><div><strong>FOCUS</strong><small>私教训练助手</small></div></div><nav><button>⌂ 工作台</button><button>◎ 学员管理</button><button className="active">▤ 训练总结</button><button>◇ 模板中心</button></nav><div className="coach"><i>冷</i><div><strong>冷教练</strong><small>专业教练</small></div></div></aside><section className="workspace"><header><div><p>训练总结 / 新建</p><h1>创建训练总结</h1></div><div><button className="ghost" onClick={load}>恢复草稿</button><button className="ghost" onClick={save}>保存草稿</button><button className="primary" onClick={download}>生成图片</button></div></header><div className="grid"><section className="form-card"><Title no="01" title="基本信息" desc="海报只展示有用的课程信息"/><div className="fields"><label>用户名<input value={course.student} onChange={e=>patch("student",e.target.value)}/></label><label>教练<input value={course.coach||"冷教练"} onChange={e=>patch("coach",e.target.value)}/></label><label className="wide">训练时间<input type="datetime-local" value={course.dateTime} onChange={e=>patch("dateTime",e.target.value)}/></label><label className="wide">本节目标<textarea rows={2} value={course.goal} onChange={e=>patch("goal",e.target.value)}/></label><CalendarPicker label="已上课日期" dateTime={course.dateTime} days={course.plannedDays||[]} onChange={v=>patch("plannedDays",v)}/><CalendarPicker label="待上课日期" dateTime={course.dateTime} days={course.missedDays||[]} onChange={v=>patch("missedDays",v)}/><CalendarPicker label="未按规划上课日期" dateTime={course.dateTime} days={course.skippedDays||[]} onChange={v=>patch("skippedDays",v)} wide/></div>
 <Title no="02" title="训练内容与完成情况" desc="最多六项，完成情况会同步到海报" compact/><div className="ex-head"><span>训练动作</span><span>组数</span><span>次数/时长</span><span>完成</span><span/></div><div className="ex-list">{course.exercises.map((x,i)=><div className="ex-row" key={i}><input value={x.name} onChange={e=>patchEx(i,"name",e.target.value)}/><input value={x.sets} onChange={e=>patchEx(i,"sets",e.target.value)}/><input value={x.reps} onChange={e=>patchEx(i,"reps",e.target.value)}/><label className="check"><input type="checkbox" checked={x.completed} onChange={e=>patchEx(i,"completed",e.target.checked)}/><span>{x.completed?"完成":"未完成"}</span></label><button aria-label="删除动作" onClick={()=>patch("exercises",course.exercises.filter((_,j)=>j!==i))}>×</button></div>)}</div><button className="add" disabled={course.exercises.length>=6} onClick={()=>patch("exercises",[...course.exercises,{name:"",sets:"3",reps:"10",completed:true}])}>＋ 添加训练动作</button>
 <Title no="03" title="身体能力雷达图" desc="当前值为实线，本节预估增长为外层虚线" compact/><div className="radar-inputs">{axes.map(a=><div key={a}><b>{a}</b><label>当前<input type="range" min="10" max="100" value={course.radar[a]} onChange={e=>patch("radar",{...course.radar,[a]:+e.target.value})}/><span>{course.radar[a]}</span></label><label>增长<input type="range" min="0" max="20" value={course.growth[a]} onChange={e=>patch("growth",{...course.growth,[a]:+e.target.value})}/><span>+{course.growth[a]}</span></label></div>)}</div>
 <Title no="04" title="本节训练肌群" desc="选择需要在正面或背面人体图中高亮的肌肉" compact/><div className="muscle-grid">{muscleGroups.map(m=><label key={m} className={(course.muscles||[]).includes(m)?"selected":""}><input type="checkbox" checked={(course.muscles||[]).includes(m)} onChange={e=>patch("muscles",e.target.checked?[...(course.muscles||[]),m]:(course.muscles||[]).filter(x=>x!==m))}/><span>{m}</span></label>)}</div>
 <Title no="05" title="教练反馈" desc="总结本节表现，并给出明确的下节方向" compact/><div className="fields"><label className="wide">教练总结<textarea rows={4} value={course.summary} onChange={e=>patch("summary",e.target.value)}/></label><label className="wide">下节计划<input value={course.nextPlan} onChange={e=>patch("nextPlan",e.target.value)}/></label></div></section><aside className="preview"><div className="preview-title"><div><h2>训练总结预览</h2><p>{course.student} · {shownTime}</p></div><span>9:16 · 1080 × 1920</span></div><div className="canvas"><canvas ref={canvas}/></div><button className="primary full" onClick={download}>↓ 下载高清图片</button><p className="privacy">所有内容当前只保存在本机浏览器。</p></aside></div></section>{notice&&<div className="toast">✓ {notice}</div>}</main>}
function Title({no,title,desc,compact=false}:{no:string;title:string;desc:string;compact?:boolean}){return <div className={`title ${compact?"compact":""}`}><span>{no}</span><div><h2>{title}</h2><p>{desc}</p></div></div>}
function CalendarPicker({label,dateTime,days,onChange,wide=false}:{label:string;dateTime:string;days:number[];onChange:(v:number[])=>void;wide?:boolean}){const[open,setOpen]=useState(false),base=new Date(dateTime||nowLocal()),year=base.getFullYear(),month=base.getMonth(),count=new Date(year,month+1,0).getDate(),start=new Date(year,month,1).getDay();return <div className={`calendar-picker ${wide?"wide":""}`}><b>{label}</b><button type="button" className="calendar-trigger" onClick={()=>setOpen(v=>!v)}>选择日期 <span>{year}年{month+1}月</span></button>{open&&<div className="calendar-pop"><strong>{year}年 {month+1}月</strong><div className="week-row">{["日","一","二","三","四","五","六"].map(x=><i key={x}>{x}</i>)}</div><div className="day-grid">{Array.from({length:start},(_,i)=><i key={`e${i}`}/>) }{Array.from({length:count},(_,i)=>i+1).map(day=><button type="button" key={day} className={days.includes(day)?"picked":""} onClick={()=>onChange(days.includes(day)?days.filter(x=>x!==day):[...days,day].sort((a,b)=>a-b))}>{day}</button>)}</div></div>}<div className="date-chips">{days.map(day=><button type="button" key={day} onClick={()=>onChange(days.filter(x=>x!==day))}>{month+1}月{day}日 ×</button>)}</div></div>}
