const AXES=["胸","背","肩","手臂","核心","腿"];
const MUSCLES=["胸大肌","肩前束","肩中束","肩后束","肱二头肌","肱三头肌","前臂","腹直肌","腹外斜肌","斜方肌","背阔肌","竖脊肌","臀大肌","臀中肌","股四头肌","内收肌","腘绳肌","胫骨前肌","腓肠肌"];
const pad=n=>String(n).padStart(2,"0");
const today=()=>{const d=new Date();return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`}};
const seed=()=>{const n=today();return {student:"王小明",coach:"冷教练",date:n.date,time:n.time,goal:"提升下肢力量与髋部稳定",doneDays:[3,6,10,13,17,20],nextDays:[23,27],missedDays:[8,15],exercises:[{name:"高脚杯深蹲",sets:"4",reps:"12",completed:true},{name:"罗马尼亚硬拉",sets:"4",reps:"10",completed:true},{name:"保加利亚分腿蹲",sets:"3",reps:"10",completed:true},{name:"平板支撑",sets:"3",reps:"45秒",completed:true}],radar:[48,58,55,52,61,64],growth:[3,3,3,3,7,9],muscles:["腹直肌","臀大肌","臀中肌","股四头肌","腘绳肌"],summary:"动作控制稳定，深蹲幅度明显提升；后两组核心略有松动，继续保持呼吸节奏。",nextPlan:"单腿稳定进阶 · 臀腿力量强化 · 核心抗旋转"}};
function calendar(course){const d=new Date(`${course.date}T00:00:00`),year=d.getFullYear(),month=d.getMonth(),count=new Date(year,month+1,0).getDate(),start=new Date(year,month,1).getDay(),cells=[];for(let i=0;i<start;i++)cells.push({empty:true,day:""});for(let day=1;day<=count;day++){let state="";if(course.doneDays.includes(day))state="done";else if(course.nextDays.includes(day))state="next";else if(course.missedDays.includes(day))state="miss";cells.push({day,state})}return {calendarTitle:`${year}年 ${month+1}月`,calendarCells:cells}}
function wrap(ctx,text,max,limit){const lines=[];let line="";for(const c of [...(text||"")]){if(ctx.measureText(line+c).width>max&&line){lines.push(line);line=c}else line+=c;if(lines.length===limit)break}if(line&&lines.length<limit)lines.push(line);return lines}
function poly(ctx,cx,cy,r,values){ctx.beginPath();values.forEach((v,i)=>{const a=-Math.PI/2+i*Math.PI/3,x=cx+Math.cos(a)*r*v/100,y=cy+Math.sin(a)*r*v/100;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath()}
Page({
 data:{tab:"edit",week:["日","一","二","三","四","五","六"],course:seed(),axes:[],muscleOptions:[],calendarTitle:"",calendarCells:[],imagePath:""},
 onLoad(){let course;try{course=tt.getStorageSync("focus-course-draft")||seed()}catch(e){course=seed()}this.refresh(course)},
 refresh(course){const cal=calendar(course);this.setData({course,...cal,axes:AXES.map((name,i)=>({name,current:course.radar[i],growth:course.growth[i]})),muscleOptions:MUSCLES.map(name=>({name,selected:course.muscles.includes(name)}))})},
 switchTab(e){const tab=e.currentTarget.dataset.tab;this.setData({tab},()=>{if(tab==="preview")setTimeout(()=>this.drawPoster(),80)})},
 changeText(e){const course={...this.data.course,[e.currentTarget.dataset.key]:e.detail.value};this.refresh(course)},
 changeDate(e){this.refresh({...this.data.course,date:e.detail.value})},changeTime(e){this.refresh({...this.data.course,time:e.detail.value})},
 cycleDay(e){const day=+e.currentTarget.dataset.day;if(!day)return;const c={...this.data.course,doneDays:[...this.data.course.doneDays],nextDays:[...this.data.course.nextDays],missedDays:[...this.data.course.missedDays]};const remove=a=>{const i=a.indexOf(day);if(i>=0)a.splice(i,1)};if(c.doneDays.includes(day)){remove(c.doneDays);c.nextDays.push(day)}else if(c.nextDays.includes(day)){remove(c.nextDays);c.missedDays.push(day)}else if(c.missedDays.includes(day)){remove(c.missedDays)}else c.doneDays.push(day);[c.doneDays,c.nextDays,c.missedDays].forEach(a=>a.sort((x,y)=>x-y));this.refresh(c)},
 changeExercise(e){const exercises=this.data.course.exercises.map((x,i)=>i===+e.currentTarget.dataset.index?{...x,[e.currentTarget.dataset.key]:e.detail.value}:x);this.refresh({...this.data.course,exercises})},
 toggleExercise(e){const exercises=this.data.course.exercises.map((x,i)=>i===+e.currentTarget.dataset.index?{...x,completed:e.detail.value}:x);this.refresh({...this.data.course,exercises})},
 addExercise(){if(this.data.course.exercises.length>=6)return tt.showToast({title:"最多六项",icon:"none"});this.refresh({...this.data.course,exercises:[...this.data.course.exercises,{name:"",sets:"3",reps:"10",completed:true}]})},
 changeRadar(e){const i=+e.currentTarget.dataset.index,kind=e.currentTarget.dataset.kind,c={...this.data.course,radar:[...this.data.course.radar],growth:[...this.data.course.growth]};c[kind][i]=+e.detail.value;this.refresh(c)},
 toggleMuscle(e){const name=MUSCLES[+e.currentTarget.dataset.index],muscles=this.data.course.muscles.includes(name)?this.data.course.muscles.filter(x=>x!==name):[...this.data.course.muscles,name];this.refresh({...this.data.course,muscles})},
 saveDraft(){tt.setStorageSync("focus-course-draft",this.data.course);tt.showToast({title:"草稿已保存",icon:"success"})},
 renderPoster(){this.saveDraft();this.setData({tab:"preview"},()=>setTimeout(()=>this.drawPoster(),80))},
 drawPoster(){const c=this.data.course,ctx=tt.createCanvasContext("poster",this),lime="#b7db3f",white="#f5f5f2",ink="#050505",S=.5;ctx.scale(S,S);ctx.setFillStyle(ink);ctx.fillRect(0,0,1080,1920);ctx.setLineWidth(2);ctx.setStrokeStyle("#656560");ctx.beginPath();ctx.moveTo(214,50);ctx.lineTo(214,232);ctx.stroke();
   ctx.setStrokeStyle(lime);ctx.setLineWidth(7);[[62,62,90,62],[62,62,62,90],[175,62,147,62],[175,62,175,90],[62,170,62,142],[62,170,90,170],[175,170,147,170],[175,170,175,142]].forEach(p=>{ctx.beginPath();ctx.moveTo(p[0],p[1]);ctx.lineTo(p[2],p[3]);ctx.stroke()});ctx.setFillStyle(lime);ctx.setFontSize(24);ctx.fillText("FOCUS",65,204);ctx.setFontSize(19);ctx.fillText("健身",92,226);
   ctx.setFillStyle(white);ctx.setFontSize(70);ctx.fillText(c.student||"未命名",252,145);ctx.setFillStyle("#a7a7a1");ctx.setFontSize(22);ctx.fillText(`教练：${c.coach||""}`,255,190);ctx.setTextAlign("right");ctx.setFillStyle(white);ctx.setFontSize(29);ctx.fillText(`${c.date.replace(/-/g,".")}  ${c.time}`,1018,145);ctx.setTextAlign("left");ctx.setStrokeStyle(lime);ctx.beginPath();ctx.moveTo(55,251);ctx.lineTo(615,251);ctx.lineTo(688,200);ctx.lineTo(1018,200);ctx.stroke();
   ctx.beginPath();ctx.moveTo(55,292);ctx.lineTo(936,292);ctx.lineTo(1018,335);ctx.lineTo(1018,410);ctx.lineTo(55,410);ctx.closePath();ctx.stroke();ctx.beginPath();ctx.moveTo(55,292);ctx.lineTo(322,292);ctx.lineTo(275,410);ctx.lineTo(55,410);ctx.closePath();ctx.setFillStyle(lime);ctx.fill();ctx.setFillStyle(ink);ctx.setFontSize(36);ctx.fillText("本节目标",83,365);ctx.setFillStyle(white);ctx.setFontSize(38);ctx.fillText(c.goal,340,365,610);
   this.title(ctx,"训练规划",55,500,350);this.title(ctx,"训练内容",395,500,1018);ctx.setStrokeStyle(lime);ctx.beginPath();ctx.moveTo(365,455);ctx.lineTo(365,915);ctx.stroke();this.drawCalendar(ctx,c,65,555,270);c.exercises.slice(0,6).forEach((x,i)=>{const y=575+i*58;ctx.setFillStyle(white);ctx.setFontSize(23);ctx.fillText(x.name||"训练动作",395,y,270);ctx.setFillStyle(lime);ctx.setFontSize(21);ctx.fillText(`${x.sets||"—"}×${x.reps||"—"}`,710,y);ctx.setTextAlign("right");ctx.setFillStyle(x.completed?white:"#777");ctx.setFontSize(18);ctx.fillText(x.completed?"已完成":"未完成",985,y);ctx.setTextAlign("left");ctx.setFillStyle(x.completed?lime:"#343432");ctx.fillRect(395,y+16,520,7)});
   this.title(ctx,"能力变化图",55,980,470);this.title(ctx,"本节训练肌群",535,980,1018);ctx.setStrokeStyle(lime);ctx.beginPath();ctx.moveTo(500,940);ctx.lineTo(500,1435);ctx.stroke();this.drawRadar(ctx,c,263,1210,145);this.drawBodies(ctx,c,545,1030);
   this.block(ctx,1500,190,"教练总结",c.summary,26);this.block(ctx,1715,105,"下节计划",c.nextPlan,22);ctx.draw(false,()=>tt.canvasToTempFilePath({canvasId:"poster",destWidth:1080,destHeight:1920,success:r=>this.setData({imagePath:r.tempFilePath}),fail:()=>{}},this))},
 title(ctx,text,x,y,end){ctx.setFillStyle("#b7db3f");ctx.setFontSize(36);ctx.fillText(text,x,y);ctx.setStrokeStyle("#b7db3f");ctx.beginPath();ctx.moveTo(x,y+20);ctx.lineTo(Math.min(x+175,end-22),y+20);ctx.lineTo(Math.min(x+197,end),y-2);ctx.lineTo(end,y-2);ctx.stroke()},
 drawCalendar(ctx,c,x,y,w){const d=new Date(`${c.date}T00:00:00`),year=d.getFullYear(),month=d.getMonth(),days=new Date(year,month+1,0).getDate(),start=new Date(year,month,1).getDay(),cell=w/7;ctx.setFillStyle("#f5f5f2");ctx.setFontSize(21);ctx.fillText(`${year}年 ${month+1}月`,x,y);ctx.setFontSize(13);["日","一","二","三","四","五","六"].forEach((t,i)=>{ctx.setTextAlign("center");ctx.fillText(t,x+cell*(i+.5),y+30)});for(let day=1;day<=days;day++){const n=start+day-1,cx=x+cell*(n%7+.5),cy=y+57+Math.floor(n/7)*34,done=c.doneDays.includes(day),next=c.nextDays.includes(day),miss=c.missedDays.includes(day);if(done||next||miss){ctx.beginPath();ctx.arc(cx,cy-5,12,0,Math.PI*2);ctx.setLineWidth(2);ctx.setStrokeStyle(miss?"#ff2ca8":"#b7db3f");if(done||miss){ctx.setFillStyle(miss?"#ff2ca8":"#b7db3f");ctx.fill()}else ctx.stroke()}ctx.setFillStyle(done?"#050505":"#f5f5f2");ctx.setFontSize(13);ctx.fillText(String(day),cx,cy)}ctx.setTextAlign("left")},
 drawRadar(ctx,c,cx,cy,r){ctx.setStrokeStyle("#575752");ctx.setLineWidth(1);for(let l=1;l<=5;l++){poly(ctx,cx,cy,r,AXES.map(()=>l*20));ctx.stroke()}AXES.forEach((a,i)=>{const q=-Math.PI/2+i*Math.PI/3;ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(q)*r,cy+Math.sin(q)*r);ctx.stroke();ctx.setFillStyle("#f5f5f2");ctx.setFontSize(18);ctx.setTextAlign("center");ctx.fillText(a,cx+Math.cos(q)*(r+30),cy+Math.sin(q)*(r+30))});poly(ctx,cx,cy,r,c.radar);ctx.setFillStyle("rgba(183,219,63,.38)");ctx.fill();ctx.setStrokeStyle("#b7db3f");ctx.setLineWidth(3);ctx.stroke();poly(ctx,cx,cy,r,c.radar.map((x,i)=>Math.min(100,x+c.growth[i])));ctx.setLineDash([12,10]);ctx.stroke();ctx.setLineDash([]);AXES.forEach((a,i)=>{const q=-Math.PI/2+i*Math.PI/3,iv=c.radar[i],ov=Math.min(100,iv+c.growth[i]);ctx.setFontSize(14);ctx.setFillStyle("#f5f5f2");ctx.fillText(String(iv),cx+Math.cos(q)*r*iv/100,cy+Math.sin(q)*r*iv/100);ctx.setFillStyle("#b7db3f");ctx.fillText(String(ov),cx+Math.cos(q)*(r*ov/100+16),cy+Math.sin(q)*(r*ov/100+16))});ctx.setTextAlign("left")},
 drawBodies(ctx,c,x,y){const selected=new Set(c.muscles),lime="#b7db3f",off="#292925";const body=(cx,back)=>{ctx.setStrokeStyle("#696961");ctx.setFillStyle(off);ctx.beginPath();ctx.arc(cx,y+28,18,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillRect(cx-9,y+45,18,18);ctx.beginPath();ctx.moveTo(cx-12,y+60);ctx.lineTo(cx-45,y+80);ctx.lineTo(cx-28,y+215);ctx.lineTo(cx+28,y+215);ctx.lineTo(cx+45,y+80);ctx.closePath();ctx.fill();ctx.stroke();ctx.setLineWidth(18);[[-43,82,-58,185],[43,82,58,185],[-18,210,-25,340],[18,210,25,340]].forEach(p=>{ctx.beginPath();ctx.moveTo(cx+p[0],y+p[1]);ctx.lineTo(cx+p[2],y+p[3]);ctx.stroke()});const spot=(name,px,py,rx,ry)=>{ctx.beginPath();ctx.setFillStyle(selected.has(name)?lime:"#3a3a35");ctx.ellipse(cx+px,y+py,rx,ry,0,0,Math.PI*2);ctx.fill()};if(!back){spot("胸大肌",-15,96,17,15);spot("胸大肌",15,96,17,15);spot("肩前束",-38,83,10,14);spot("肩前束",38,83,10,14);spot("腹直肌",0,150,12,43);spot("股四头肌",-20,260,10,38);spot("股四头肌",20,260,10,38)}else{spot("肩后束",-38,84,11,14);spot("肩后束",38,84,11,14);spot("斜方肌",0,100,23,28);spot("背阔肌",-22,145,14,38);spot("背阔肌",22,145,14,38);spot("臀大肌",-17,222,16,18);spot("臀大肌",17,222,16,18);spot("腘绳肌",-20,270,9,35);spot("腘绳肌",20,270,9,35)}ctx.setFillStyle("#aaa9a2");ctx.setFontSize(15);ctx.setTextAlign("center");ctx.fillText(back?"背面":"正面",cx,y+380)};body(x+105,false);body(x+315,true);ctx.setTextAlign("left");ctx.setFillStyle("#f5f5f2");ctx.setFontSize(16);ctx.fillText(c.muscles.join(" · "),x+5,y+420,450)},
 block(ctx,y,h,title,text,font){ctx.beginPath();ctx.moveTo(55,y);ctx.lineTo(937,y);ctx.lineTo(1018,y+42);ctx.lineTo(1018,y+h);ctx.lineTo(55,y+h);ctx.closePath();ctx.setStrokeStyle("#b7db3f");ctx.setLineWidth(2);ctx.stroke();ctx.setFillStyle("#b7db3f");ctx.setFontSize(h<120?30:38);ctx.fillText(title,85,h<120?y+42:y+60);ctx.beginPath();ctx.moveTo(h<120?270:300,h<120?y+34:y+49);ctx.lineTo(920,h<120?y+34:y+49);ctx.stroke();ctx.setFillStyle("#f5f5f2");ctx.setFontSize(font);wrap(ctx,text,860,h>160?3:1).forEach((line,i)=>ctx.fillText(line,85,(h<120?y+82:y+112)+i*39))},
 saveImage(){if(!this.data.imagePath)return this.drawPoster();tt.saveImageToPhotosAlbum({filePath:this.data.imagePath,success:()=>tt.showToast({title:"已保存到相册",icon:"success"}),fail:()=>tt.showToast({title:"请允许保存图片",icon:"none"})})}
})
